# Generated by Django 3.1.6 on 2022-01-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(default='CodeWithSujay', max_length=30)),
                ('home_subtitle', models.CharField(default='Professional Website', max_length=500)),
                ('tech_desc', models.CharField(default='No Description Available', max_length=5000)),
                ('total_student', models.IntegerField(default=0)),
                ('total_course', models.IntegerField(default=0)),
                ('total_review', models.IntegerField(default=0)),
                ('video_desc', models.CharField(max_length=500)),
                ('video_url', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
