# Generated by Django 3.1.6 on 2022-01-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20220102_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
